### ISSUE TITLE
Example on Readme

### ISSUE THREAD

**Issue by diazgilberto** [singhcool/deno-swagger-doc#6]
Hi 👋 ,

I'm trying to make this work. I followed the readme to setup the module. I did it inside the root `mod.ts` since that is my assumption. Can you give an example how to comment out a `app.get(...)` or `app.post(...)`?

**Comment by singhcool** [comment]
Hi, 

 Please below repo. I have implemented the swagger documentation using this package.
[Deno with Rest API](https://github.com/singhcool/Deno-Sample-App)

**Comment by diazgilberto** [comment]
Thanks,
this is very useful.

**Comment by diazgilberto** [comment]
I don't understand. I can't find in [this app](https://github.com/singhcool/Deno-Sample-App) where are you using this module. My understanding of this module is that you have to include it inside your `app.ts`. In your `Deno-Sample-App` you are not doing that.

**Comment by singhcool** [comment]
Hi @diazgilberto ,

Once run the deno app, Please check this router url [swagger docs url](http://localhost:8000/api-docs)

**Comment by singhcool** [comment]
@diazgilberto Can I close this issue?

**Comment by chansdad** [comment]
unfortunately , this app is not starting . when i run it , i get the following error after a bunch of downloads 
ownload https://dev.jspm.io/npm:js-yaml@3.14.1/lib/js-yaml/common.dew.js
Download https://dev.jspm.io/npm:js-yaml@3.14.1/lib/js-yaml/type/timestamp.dew.js
Download https://dev.jspm.io/npm:js-yaml@3.14.1/lib/js-yaml/type/null.dew.js
Download https://dev.jspm.io/npm:js-yaml@3.14.1/lib/js-yaml/type/js/undefined.dew.js
**Warning std versions prefixed with 'v' were deprecated recently. Please change your import to https://deno.land/std@0.50.0/path/mod.ts (at https://deno.land/std@v0.50.0/path/mod.ts)
error: Import 'https://deno.land/std@v0.50.0/path/mod.ts' failed: 404 Not Found
    at https://deno.land/x/plugin_prepare@v0.6.0/deps.ts:3:0**
